// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/gimalay/octogo/todoapp/binding/command.proto

package binding

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommandType int32

const (
	CommandType_Unknown       CommandType = 0
	CommandType_NewTask       CommandType = 3327
	CommandType_NewProject    CommandType = 1947
	CommandType_RemoveTask    CommandType = 3687
	CommandType_AddTask       CommandType = 2150
	CommandType_RenameProject CommandType = 4662
	CommandType_DeleteProject CommandType = 1898
	CommandType_RenameTask    CommandType = 3442
)

var CommandType_name = map[int32]string{
	0:    "Unknown",
	3327: "NewTask",
	1947: "NewProject",
	3687: "RemoveTask",
	2150: "AddTask",
	4662: "RenameProject",
	1898: "DeleteProject",
	3442: "RenameTask",
}

var CommandType_value = map[string]int32{
	"Unknown":       0,
	"NewTask":       3327,
	"NewProject":    1947,
	"RemoveTask":    3687,
	"AddTask":       2150,
	"RenameProject": 4662,
	"DeleteProject": 1898,
	"RenameTask":    3442,
}

func (x CommandType) String() string {
	return proto.EnumName(CommandType_name, int32(x))
}

func (CommandType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f251ae2394bc7f3, []int{0}
}

type Command struct {
	Type                 CommandType          `protobuf:"varint,1,opt,name=type,proto3,enum=binding.CommandType" json:"type,omitempty"`
	Payload              []byte               `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f251ae2394bc7f3, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetType() CommandType {
	if m != nil {
		return m.Type
	}
	return CommandType_Unknown
}

func (m *Command) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Command) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Command_NewProject struct {
	ProjectID            []byte   `protobuf:"bytes,8589,opt,name=projectID,proto3" json:"projectID,omitempty"`
	Name                 string   `protobuf:"bytes,7669,opt,name=name,proto3" json:"name,omitempty"`
	Tasks                [][]byte `protobuf:"bytes,2463,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command_NewProject) Reset()         { *m = Command_NewProject{} }
func (m *Command_NewProject) String() string { return proto.CompactTextString(m) }
func (*Command_NewProject) ProtoMessage()    {}
func (*Command_NewProject) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f251ae2394bc7f3, []int{0, 0}
}

func (m *Command_NewProject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command_NewProject.Unmarshal(m, b)
}
func (m *Command_NewProject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command_NewProject.Marshal(b, m, deterministic)
}
func (m *Command_NewProject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command_NewProject.Merge(m, src)
}
func (m *Command_NewProject) XXX_Size() int {
	return xxx_messageInfo_Command_NewProject.Size(m)
}
func (m *Command_NewProject) XXX_DiscardUnknown() {
	xxx_messageInfo_Command_NewProject.DiscardUnknown(m)
}

var xxx_messageInfo_Command_NewProject proto.InternalMessageInfo

func (m *Command_NewProject) GetProjectID() []byte {
	if m != nil {
		return m.ProjectID
	}
	return nil
}

func (m *Command_NewProject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command_NewProject) GetTasks() [][]byte {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type Command_NewTask struct {
	TaskID               []byte   `protobuf:"bytes,3324,opt,name=taskID,proto3" json:"taskID,omitempty"`
	Name                 string   `protobuf:"bytes,7669,opt,name=name,proto3" json:"name,omitempty"`
	Emoji                string   `protobuf:"bytes,5259,opt,name=emoji,proto3" json:"emoji,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command_NewTask) Reset()         { *m = Command_NewTask{} }
func (m *Command_NewTask) String() string { return proto.CompactTextString(m) }
func (*Command_NewTask) ProtoMessage()    {}
func (*Command_NewTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f251ae2394bc7f3, []int{0, 1}
}

func (m *Command_NewTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command_NewTask.Unmarshal(m, b)
}
func (m *Command_NewTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command_NewTask.Marshal(b, m, deterministic)
}
func (m *Command_NewTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command_NewTask.Merge(m, src)
}
func (m *Command_NewTask) XXX_Size() int {
	return xxx_messageInfo_Command_NewTask.Size(m)
}
func (m *Command_NewTask) XXX_DiscardUnknown() {
	xxx_messageInfo_Command_NewTask.DiscardUnknown(m)
}

var xxx_messageInfo_Command_NewTask proto.InternalMessageInfo

func (m *Command_NewTask) GetTaskID() []byte {
	if m != nil {
		return m.TaskID
	}
	return nil
}

func (m *Command_NewTask) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command_NewTask) GetEmoji() string {
	if m != nil {
		return m.Emoji
	}
	return ""
}

type Command_RemoveTask struct {
	ProjectID            []byte   `protobuf:"bytes,9326,opt,name=projectID,proto3" json:"projectID,omitempty"`
	TaskID               []byte   `protobuf:"bytes,8534,opt,name=taskID,proto3" json:"taskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command_RemoveTask) Reset()         { *m = Command_RemoveTask{} }
func (m *Command_RemoveTask) String() string { return proto.CompactTextString(m) }
func (*Command_RemoveTask) ProtoMessage()    {}
func (*Command_RemoveTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f251ae2394bc7f3, []int{0, 2}
}

func (m *Command_RemoveTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command_RemoveTask.Unmarshal(m, b)
}
func (m *Command_RemoveTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command_RemoveTask.Marshal(b, m, deterministic)
}
func (m *Command_RemoveTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command_RemoveTask.Merge(m, src)
}
func (m *Command_RemoveTask) XXX_Size() int {
	return xxx_messageInfo_Command_RemoveTask.Size(m)
}
func (m *Command_RemoveTask) XXX_DiscardUnknown() {
	xxx_messageInfo_Command_RemoveTask.DiscardUnknown(m)
}

var xxx_messageInfo_Command_RemoveTask proto.InternalMessageInfo

func (m *Command_RemoveTask) GetProjectID() []byte {
	if m != nil {
		return m.ProjectID
	}
	return nil
}

func (m *Command_RemoveTask) GetTaskID() []byte {
	if m != nil {
		return m.TaskID
	}
	return nil
}

type Command_DeleteProject struct {
	ProjectID            []byte   `protobuf:"bytes,9326,opt,name=projectID,proto3" json:"projectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command_DeleteProject) Reset()         { *m = Command_DeleteProject{} }
func (m *Command_DeleteProject) String() string { return proto.CompactTextString(m) }
func (*Command_DeleteProject) ProtoMessage()    {}
func (*Command_DeleteProject) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f251ae2394bc7f3, []int{0, 3}
}

func (m *Command_DeleteProject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command_DeleteProject.Unmarshal(m, b)
}
func (m *Command_DeleteProject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command_DeleteProject.Marshal(b, m, deterministic)
}
func (m *Command_DeleteProject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command_DeleteProject.Merge(m, src)
}
func (m *Command_DeleteProject) XXX_Size() int {
	return xxx_messageInfo_Command_DeleteProject.Size(m)
}
func (m *Command_DeleteProject) XXX_DiscardUnknown() {
	xxx_messageInfo_Command_DeleteProject.DiscardUnknown(m)
}

var xxx_messageInfo_Command_DeleteProject proto.InternalMessageInfo

func (m *Command_DeleteProject) GetProjectID() []byte {
	if m != nil {
		return m.ProjectID
	}
	return nil
}

type Command_AddTask struct {
	ProjectID            []byte   `protobuf:"bytes,8326,opt,name=projectID,proto3" json:"projectID,omitempty"`
	TaskID               []byte   `protobuf:"bytes,4534,opt,name=taskID,proto3" json:"taskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command_AddTask) Reset()         { *m = Command_AddTask{} }
func (m *Command_AddTask) String() string { return proto.CompactTextString(m) }
func (*Command_AddTask) ProtoMessage()    {}
func (*Command_AddTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f251ae2394bc7f3, []int{0, 4}
}

func (m *Command_AddTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command_AddTask.Unmarshal(m, b)
}
func (m *Command_AddTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command_AddTask.Marshal(b, m, deterministic)
}
func (m *Command_AddTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command_AddTask.Merge(m, src)
}
func (m *Command_AddTask) XXX_Size() int {
	return xxx_messageInfo_Command_AddTask.Size(m)
}
func (m *Command_AddTask) XXX_DiscardUnknown() {
	xxx_messageInfo_Command_AddTask.DiscardUnknown(m)
}

var xxx_messageInfo_Command_AddTask proto.InternalMessageInfo

func (m *Command_AddTask) GetProjectID() []byte {
	if m != nil {
		return m.ProjectID
	}
	return nil
}

func (m *Command_AddTask) GetTaskID() []byte {
	if m != nil {
		return m.TaskID
	}
	return nil
}

type Command_RenameProject struct {
	ProjectID            []byte   `protobuf:"bytes,6326,opt,name=projectID,proto3" json:"projectID,omitempty"`
	Name                 string   `protobuf:"bytes,9222,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command_RenameProject) Reset()         { *m = Command_RenameProject{} }
func (m *Command_RenameProject) String() string { return proto.CompactTextString(m) }
func (*Command_RenameProject) ProtoMessage()    {}
func (*Command_RenameProject) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f251ae2394bc7f3, []int{0, 5}
}

func (m *Command_RenameProject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command_RenameProject.Unmarshal(m, b)
}
func (m *Command_RenameProject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command_RenameProject.Marshal(b, m, deterministic)
}
func (m *Command_RenameProject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command_RenameProject.Merge(m, src)
}
func (m *Command_RenameProject) XXX_Size() int {
	return xxx_messageInfo_Command_RenameProject.Size(m)
}
func (m *Command_RenameProject) XXX_DiscardUnknown() {
	xxx_messageInfo_Command_RenameProject.DiscardUnknown(m)
}

var xxx_messageInfo_Command_RenameProject proto.InternalMessageInfo

func (m *Command_RenameProject) GetProjectID() []byte {
	if m != nil {
		return m.ProjectID
	}
	return nil
}

func (m *Command_RenameProject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Command_RenameTask struct {
	TaskID               []byte   `protobuf:"bytes,8326,opt,name=taskID,proto3" json:"taskID,omitempty"`
	Name                 string   `protobuf:"bytes,9292,opt,name=name,proto3" json:"name,omitempty"`
	Emoji                string   `protobuf:"bytes,4494,opt,name=emoji,proto3" json:"emoji,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command_RenameTask) Reset()         { *m = Command_RenameTask{} }
func (m *Command_RenameTask) String() string { return proto.CompactTextString(m) }
func (*Command_RenameTask) ProtoMessage()    {}
func (*Command_RenameTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f251ae2394bc7f3, []int{0, 6}
}

func (m *Command_RenameTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command_RenameTask.Unmarshal(m, b)
}
func (m *Command_RenameTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command_RenameTask.Marshal(b, m, deterministic)
}
func (m *Command_RenameTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command_RenameTask.Merge(m, src)
}
func (m *Command_RenameTask) XXX_Size() int {
	return xxx_messageInfo_Command_RenameTask.Size(m)
}
func (m *Command_RenameTask) XXX_DiscardUnknown() {
	xxx_messageInfo_Command_RenameTask.DiscardUnknown(m)
}

var xxx_messageInfo_Command_RenameTask proto.InternalMessageInfo

func (m *Command_RenameTask) GetTaskID() []byte {
	if m != nil {
		return m.TaskID
	}
	return nil
}

func (m *Command_RenameTask) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command_RenameTask) GetEmoji() string {
	if m != nil {
		return m.Emoji
	}
	return ""
}

func init() {
	proto.RegisterEnum("binding.CommandType", CommandType_name, CommandType_value)
	proto.RegisterType((*Command)(nil), "binding.Command")
	proto.RegisterType((*Command_NewProject)(nil), "binding.Command.NewProject")
	proto.RegisterType((*Command_NewTask)(nil), "binding.Command.NewTask")
	proto.RegisterType((*Command_RemoveTask)(nil), "binding.Command.RemoveTask")
	proto.RegisterType((*Command_DeleteProject)(nil), "binding.Command.DeleteProject")
	proto.RegisterType((*Command_AddTask)(nil), "binding.Command.AddTask")
	proto.RegisterType((*Command_RenameProject)(nil), "binding.Command.RenameProject")
	proto.RegisterType((*Command_RenameTask)(nil), "binding.Command.RenameTask")
}

func init() {
	proto.RegisterFile("github.com/gimalay/octogo/todoapp/binding/command.proto", fileDescriptor_8f251ae2394bc7f3)
}

var fileDescriptor_8f251ae2394bc7f3 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x3f, 0x6f, 0xd3, 0x40,
	0x14, 0xaf, 0x9b, 0xb6, 0x56, 0x5e, 0xd2, 0xf6, 0x74, 0x05, 0x71, 0x3d, 0x81, 0xb0, 0x28, 0x83,
	0x61, 0xb0, 0x45, 0x19, 0x40, 0x62, 0x4a, 0x93, 0x21, 0x5d, 0x22, 0xb0, 0x82, 0x98, 0x2f, 0xf1,
	0x61, 0xdc, 0xe4, 0xfc, 0xac, 0xe6, 0x4a, 0x94, 0x91, 0xa5, 0x0b, 0x02, 0x89, 0x99, 0x81, 0x6f,
	0x91, 0x81, 0xcf, 0xc0, 0xcc, 0x47, 0x00, 0x89, 0x81, 0x01, 0x89, 0x0d, 0x89, 0xca, 0x7f, 0x52,
	0x27, 0x4e, 0xb2, 0xdd, 0xfb, 0xf9, 0xf9, 0xf7, 0xef, 0x0e, 0x9e, 0x04, 0xa1, 0x7e, 0x73, 0xd1,
	0x73, 0xfa, 0xa8, 0xdc, 0x20, 0x54, 0x62, 0x28, 0x26, 0x2e, 0xf6, 0x35, 0x06, 0xe8, 0x6a, 0xf4,
	0x51, 0xc4, 0xb1, 0xdb, 0x0b, 0x23, 0x3f, 0x8c, 0x02, 0xb7, 0x8f, 0x4a, 0x89, 0xc8, 0x77, 0xe2,
	0x73, 0xd4, 0x48, 0xcd, 0x1c, 0xe6, 0x77, 0x03, 0xc4, 0x60, 0x28, 0xdd, 0x14, 0xee, 0x5d, 0xbc,
	0x76, 0x75, 0xa8, 0xe4, 0x48, 0x0b, 0x15, 0x67, 0x9b, 0xf7, 0xde, 0x6d, 0x83, 0xd9, 0xcc, 0xfe,
	0xa5, 0x36, 0x6c, 0xe9, 0x49, 0x2c, 0x99, 0x61, 0x19, 0xf6, 0xde, 0xf1, 0x0d, 0x27, 0x27, 0x71,
	0xf2, 0xef, 0xdd, 0x49, 0x2c, 0xbd, 0x74, 0x83, 0x32, 0x30, 0x63, 0x31, 0x19, 0xa2, 0xf0, 0xd9,
	0xa6, 0x65, 0xd8, 0x75, 0x6f, 0x36, 0xd2, 0xa7, 0x50, 0xbd, 0x96, 0x60, 0x15, 0xcb, 0xb0, 0x6b,
	0xc7, 0xdc, 0xc9, 0x4c, 0x38, 0x33, 0x13, 0x4e, 0x77, 0xb6, 0xe1, 0x15, 0xcb, 0xfc, 0x15, 0x40,
	0x47, 0x8e, 0x9f, 0x9f, 0xe3, 0x99, 0xec, 0x6b, 0x7a, 0x07, 0xaa, 0x71, 0x76, 0x3c, 0x6d, 0xb1,
	0x0f, 0xcd, 0x54, 0xa4, 0x40, 0xe8, 0x01, 0x6c, 0x45, 0x42, 0x49, 0xf6, 0xf7, 0x99, 0x65, 0xd8,
	0x55, 0x2f, 0x1d, 0xe8, 0x4d, 0xd8, 0xd6, 0x62, 0x34, 0x18, 0xb1, 0x2f, 0x07, 0x56, 0xc5, 0xae,
	0x7b, 0xd9, 0xc4, 0x3b, 0x60, 0x76, 0xe4, 0xb8, 0x2b, 0x46, 0x03, 0x7a, 0x0b, 0x76, 0x12, 0xec,
	0xb4, 0xc5, 0xfe, 0x1d, 0xa6, 0x94, 0xf9, 0xb8, 0x96, 0x4f, 0x2a, 0x3c, 0x0b, 0xd9, 0xfb, 0x07,
	0x29, 0x9a, 0x4d, 0xbc, 0x05, 0xe0, 0x49, 0x85, 0x6f, 0x65, 0x4a, 0xb9, 0x60, 0xf4, 0x77, 0xbb,
	0x6c, 0xb4, 0x50, 0xfc, 0x7e, 0x32, 0xaf, 0xc8, 0x1d, 0xd8, 0x6d, 0xc9, 0xa1, 0xd4, 0x72, 0x65,
	0xe2, 0x25, 0x22, 0xde, 0x00, 0xb3, 0xe1, 0xfb, 0xcb, 0x92, 0x97, 0x8d, 0xf5, 0x92, 0xd3, 0xa3,
	0x05, 0xc9, 0x26, 0xec, 0x7a, 0x32, 0x49, 0xb6, 0x52, 0x72, 0xfa, 0x68, 0x5d, 0xc9, 0x97, 0xed,
	0xa2, 0x14, 0xfe, 0x22, 0x49, 0x9f, 0x9c, 0x4a, 0x85, 0xe6, 0x3e, 0xca, 0x85, 0x7e, 0x6b, 0xaf,
	0x2a, 0xf4, 0xe3, 0xd1, 0x5c, 0xa1, 0x0f, 0x3f, 0x19, 0x50, 0x9b, 0x7b, 0x63, 0xb4, 0x06, 0xe6,
	0xcb, 0x68, 0x10, 0xe1, 0x38, 0x22, 0x1b, 0xb4, 0x7e, 0x7d, 0x7b, 0xe4, 0xff, 0x21, 0xdd, 0x9f,
	0x7f, 0x24, 0xe4, 0xf3, 0x7e, 0x02, 0x14, 0x97, 0x41, 0x7e, 0xde, 0x4e, 0xf6, 0xf3, 0x9e, 0xc8,
	0x0f, 0x42, 0x69, 0x29, 0x32, 0x99, 0xde, 0x4f, 0xb0, 0x85, 0xe6, 0xc9, 0xaf, 0xbd, 0x8c, 0x66,
	0x96, 0x8a, 0xfc, 0xe1, 0x27, 0x95, 0xaf, 0x9b, 0x1b, 0xbd, 0x9d, 0xf4, 0xc5, 0x3e, 0xbe, 0x0a,
	0x00, 0x00, 0xff, 0xff, 0x1c, 0x81, 0x5d, 0x88, 0x88, 0x03, 0x00, 0x00,
}
