// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/gimalay/octogo/todoapp/model/event.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_Unknown EventType = 0
	// Project
	EventType_ProjectCreated EventType = 8812
	EventType_ProjectRenamed EventType = 8489
	EventType_ProjectDeleted EventType = 6094
	EventType_TaskAdded      EventType = 1541
	EventType_TaskRemoved    EventType = 4982
	// Task
	EventType_TaskImported EventType = 1036
	EventType_TaskCreated  EventType = 8694
	EventType_TaskRenamed  EventType = 5239
)

var EventType_name = map[int32]string{
	0:    "Unknown",
	8812: "ProjectCreated",
	8489: "ProjectRenamed",
	6094: "ProjectDeleted",
	1541: "TaskAdded",
	4982: "TaskRemoved",
	1036: "TaskImported",
	8694: "TaskCreated",
	5239: "TaskRenamed",
}

var EventType_value = map[string]int32{
	"Unknown":        0,
	"ProjectCreated": 8812,
	"ProjectRenamed": 8489,
	"ProjectDeleted": 6094,
	"TaskAdded":      1541,
	"TaskRemoved":    4982,
	"TaskImported":   1036,
	"TaskCreated":    8694,
	"TaskRenamed":    5239,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_55f057e723007719, []int{0}
}

type AggregateType int32

const (
	AggregateType_UnknownAggregate AggregateType = 0
	AggregateType_Project          AggregateType = 3756
	AggregateType_Task             AggregateType = 8068
)

var AggregateType_name = map[int32]string{
	0:    "UnknownAggregate",
	3756: "Project",
	8068: "Task",
}

var AggregateType_value = map[string]int32{
	"UnknownAggregate": 0,
	"Project":          3756,
	"Task":             8068,
}

func (x AggregateType) String() string {
	return proto.EnumName(AggregateType_name, int32(x))
}

func (AggregateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_55f057e723007719, []int{1}
}

type Event struct {
	ID                   uint64               `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PreviousMessageHash  []byte               `protobuf:"bytes,2,opt,name=previousMessageHash,proto3" json:"previousMessageHash,omitempty"`
	AggregateID          []byte               `protobuf:"bytes,3,opt,name=aggregateID,proto3" json:"aggregateID,omitempty"`
	AggregateType        AggregateType        `protobuf:"varint,4,opt,name=aggregateType,proto3,enum=model.AggregateType" json:"aggregateType,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourceID             []byte               `protobuf:"bytes,6,opt,name=sourceID,proto3" json:"sourceID,omitempty"`
	SourceVersion        int32                `protobuf:"varint,7,opt,name=sourceVersion,proto3" json:"sourceVersion,omitempty"`
	Type                 EventType            `protobuf:"varint,8,opt,name=type,proto3,enum=model.EventType" json:"type,omitempty"`
	Payload              []byte               `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_55f057e723007719, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Event) GetPreviousMessageHash() []byte {
	if m != nil {
		return m.PreviousMessageHash
	}
	return nil
}

func (m *Event) GetAggregateID() []byte {
	if m != nil {
		return m.AggregateID
	}
	return nil
}

func (m *Event) GetAggregateType() AggregateType {
	if m != nil {
		return m.AggregateType
	}
	return AggregateType_UnknownAggregate
}

func (m *Event) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Event) GetSourceID() []byte {
	if m != nil {
		return m.SourceID
	}
	return nil
}

func (m *Event) GetSourceVersion() int32 {
	if m != nil {
		return m.SourceVersion
	}
	return 0
}

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_Unknown
}

func (m *Event) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Event_ProjectCreated struct {
	Name                 string   `protobuf:"bytes,2825,opt,name=name,proto3" json:"name,omitempty"`
	Tasks                [][]byte `protobuf:"bytes,9477,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_ProjectCreated) Reset()         { *m = Event_ProjectCreated{} }
func (m *Event_ProjectCreated) String() string { return proto.CompactTextString(m) }
func (*Event_ProjectCreated) ProtoMessage()    {}
func (*Event_ProjectCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_55f057e723007719, []int{0, 0}
}

func (m *Event_ProjectCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_ProjectCreated.Unmarshal(m, b)
}
func (m *Event_ProjectCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_ProjectCreated.Marshal(b, m, deterministic)
}
func (m *Event_ProjectCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_ProjectCreated.Merge(m, src)
}
func (m *Event_ProjectCreated) XXX_Size() int {
	return xxx_messageInfo_Event_ProjectCreated.Size(m)
}
func (m *Event_ProjectCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_ProjectCreated.DiscardUnknown(m)
}

var xxx_messageInfo_Event_ProjectCreated proto.InternalMessageInfo

func (m *Event_ProjectCreated) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event_ProjectCreated) GetTasks() [][]byte {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type Event_TaskRemoved struct {
	TaskID               []byte   `protobuf:"bytes,2296,opt,name=taskID,proto3" json:"taskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_TaskRemoved) Reset()         { *m = Event_TaskRemoved{} }
func (m *Event_TaskRemoved) String() string { return proto.CompactTextString(m) }
func (*Event_TaskRemoved) ProtoMessage()    {}
func (*Event_TaskRemoved) Descriptor() ([]byte, []int) {
	return fileDescriptor_55f057e723007719, []int{0, 1}
}

func (m *Event_TaskRemoved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_TaskRemoved.Unmarshal(m, b)
}
func (m *Event_TaskRemoved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_TaskRemoved.Marshal(b, m, deterministic)
}
func (m *Event_TaskRemoved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_TaskRemoved.Merge(m, src)
}
func (m *Event_TaskRemoved) XXX_Size() int {
	return xxx_messageInfo_Event_TaskRemoved.Size(m)
}
func (m *Event_TaskRemoved) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_TaskRemoved.DiscardUnknown(m)
}

var xxx_messageInfo_Event_TaskRemoved proto.InternalMessageInfo

func (m *Event_TaskRemoved) GetTaskID() []byte {
	if m != nil {
		return m.TaskID
	}
	return nil
}

type Event_TaskAdded struct {
	TaskID               []byte   `protobuf:"bytes,6339,opt,name=taskID,proto3" json:"taskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_TaskAdded) Reset()         { *m = Event_TaskAdded{} }
func (m *Event_TaskAdded) String() string { return proto.CompactTextString(m) }
func (*Event_TaskAdded) ProtoMessage()    {}
func (*Event_TaskAdded) Descriptor() ([]byte, []int) {
	return fileDescriptor_55f057e723007719, []int{0, 2}
}

func (m *Event_TaskAdded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_TaskAdded.Unmarshal(m, b)
}
func (m *Event_TaskAdded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_TaskAdded.Marshal(b, m, deterministic)
}
func (m *Event_TaskAdded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_TaskAdded.Merge(m, src)
}
func (m *Event_TaskAdded) XXX_Size() int {
	return xxx_messageInfo_Event_TaskAdded.Size(m)
}
func (m *Event_TaskAdded) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_TaskAdded.DiscardUnknown(m)
}

var xxx_messageInfo_Event_TaskAdded proto.InternalMessageInfo

func (m *Event_TaskAdded) GetTaskID() []byte {
	if m != nil {
		return m.TaskID
	}
	return nil
}

type Event_ProjectRenamed struct {
	Name                 string   `protobuf:"bytes,8825,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_ProjectRenamed) Reset()         { *m = Event_ProjectRenamed{} }
func (m *Event_ProjectRenamed) String() string { return proto.CompactTextString(m) }
func (*Event_ProjectRenamed) ProtoMessage()    {}
func (*Event_ProjectRenamed) Descriptor() ([]byte, []int) {
	return fileDescriptor_55f057e723007719, []int{0, 3}
}

func (m *Event_ProjectRenamed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_ProjectRenamed.Unmarshal(m, b)
}
func (m *Event_ProjectRenamed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_ProjectRenamed.Marshal(b, m, deterministic)
}
func (m *Event_ProjectRenamed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_ProjectRenamed.Merge(m, src)
}
func (m *Event_ProjectRenamed) XXX_Size() int {
	return xxx_messageInfo_Event_ProjectRenamed.Size(m)
}
func (m *Event_ProjectRenamed) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_ProjectRenamed.DiscardUnknown(m)
}

var xxx_messageInfo_Event_ProjectRenamed proto.InternalMessageInfo

func (m *Event_ProjectRenamed) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Event_ProjectDeleted struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_ProjectDeleted) Reset()         { *m = Event_ProjectDeleted{} }
func (m *Event_ProjectDeleted) String() string { return proto.CompactTextString(m) }
func (*Event_ProjectDeleted) ProtoMessage()    {}
func (*Event_ProjectDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_55f057e723007719, []int{0, 4}
}

func (m *Event_ProjectDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_ProjectDeleted.Unmarshal(m, b)
}
func (m *Event_ProjectDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_ProjectDeleted.Marshal(b, m, deterministic)
}
func (m *Event_ProjectDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_ProjectDeleted.Merge(m, src)
}
func (m *Event_ProjectDeleted) XXX_Size() int {
	return xxx_messageInfo_Event_ProjectDeleted.Size(m)
}
func (m *Event_ProjectDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_ProjectDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_Event_ProjectDeleted proto.InternalMessageInfo

type Event_TaskCreated struct {
	Name                 string   `protobuf:"bytes,3500,opt,name=name,proto3" json:"name,omitempty"`
	Emoji                string   `protobuf:"bytes,4282,opt,name=emoji,proto3" json:"emoji,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_TaskCreated) Reset()         { *m = Event_TaskCreated{} }
func (m *Event_TaskCreated) String() string { return proto.CompactTextString(m) }
func (*Event_TaskCreated) ProtoMessage()    {}
func (*Event_TaskCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_55f057e723007719, []int{0, 5}
}

func (m *Event_TaskCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_TaskCreated.Unmarshal(m, b)
}
func (m *Event_TaskCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_TaskCreated.Marshal(b, m, deterministic)
}
func (m *Event_TaskCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_TaskCreated.Merge(m, src)
}
func (m *Event_TaskCreated) XXX_Size() int {
	return xxx_messageInfo_Event_TaskCreated.Size(m)
}
func (m *Event_TaskCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_TaskCreated.DiscardUnknown(m)
}

var xxx_messageInfo_Event_TaskCreated proto.InternalMessageInfo

func (m *Event_TaskCreated) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event_TaskCreated) GetEmoji() string {
	if m != nil {
		return m.Emoji
	}
	return ""
}

type Event_TaskRenamed struct {
	Name                 string   `protobuf:"bytes,1770,opt,name=name,proto3" json:"name,omitempty"`
	Emoji                string   `protobuf:"bytes,1957,opt,name=emoji,proto3" json:"emoji,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_TaskRenamed) Reset()         { *m = Event_TaskRenamed{} }
func (m *Event_TaskRenamed) String() string { return proto.CompactTextString(m) }
func (*Event_TaskRenamed) ProtoMessage()    {}
func (*Event_TaskRenamed) Descriptor() ([]byte, []int) {
	return fileDescriptor_55f057e723007719, []int{0, 6}
}

func (m *Event_TaskRenamed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_TaskRenamed.Unmarshal(m, b)
}
func (m *Event_TaskRenamed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_TaskRenamed.Marshal(b, m, deterministic)
}
func (m *Event_TaskRenamed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_TaskRenamed.Merge(m, src)
}
func (m *Event_TaskRenamed) XXX_Size() int {
	return xxx_messageInfo_Event_TaskRenamed.Size(m)
}
func (m *Event_TaskRenamed) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_TaskRenamed.DiscardUnknown(m)
}

var xxx_messageInfo_Event_TaskRenamed proto.InternalMessageInfo

func (m *Event_TaskRenamed) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event_TaskRenamed) GetEmoji() string {
	if m != nil {
		return m.Emoji
	}
	return ""
}

func init() {
	proto.RegisterEnum("model.EventType", EventType_name, EventType_value)
	proto.RegisterEnum("model.AggregateType", AggregateType_name, AggregateType_value)
	proto.RegisterType((*Event)(nil), "model.Event")
	proto.RegisterType((*Event_ProjectCreated)(nil), "model.Event.ProjectCreated")
	proto.RegisterType((*Event_TaskRemoved)(nil), "model.Event.TaskRemoved")
	proto.RegisterType((*Event_TaskAdded)(nil), "model.Event.TaskAdded")
	proto.RegisterType((*Event_ProjectRenamed)(nil), "model.Event.ProjectRenamed")
	proto.RegisterType((*Event_ProjectDeleted)(nil), "model.Event.ProjectDeleted")
	proto.RegisterType((*Event_TaskCreated)(nil), "model.Event.TaskCreated")
	proto.RegisterType((*Event_TaskRenamed)(nil), "model.Event.TaskRenamed")
}

func init() {
	proto.RegisterFile("github.com/gimalay/octogo/todoapp/model/event.proto", fileDescriptor_55f057e723007719)
}

var fileDescriptor_55f057e723007719 = []byte{
	// 562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x3f, 0x6f, 0xd3, 0x40,
	0x18, 0xc6, 0xeb, 0x36, 0x6e, 0xea, 0x37, 0x7f, 0xb8, 0x5e, 0x0b, 0x9c, 0x8c, 0x10, 0x06, 0x95,
	0xca, 0xea, 0x60, 0x43, 0xbb, 0x00, 0x42, 0xa0, 0x52, 0x23, 0x11, 0x24, 0x24, 0x64, 0x15, 0xf6,
	0x4b, 0x7c, 0xb8, 0x6e, 0x62, 0x9f, 0x65, 0x5f, 0x82, 0xb2, 0xd3, 0x01, 0x89, 0xcf, 0xc0, 0xc6,
	0x80, 0xd4, 0x81, 0x99, 0x95, 0x9d, 0x0f, 0x82, 0x98, 0x0b, 0x6c, 0xc8, 0xe7, 0x3f, 0xb1, 0xa3,
	0x6e, 0x79, 0x9e, 0x7b, 0xde, 0x3c, 0xbf, 0xf7, 0x95, 0xe1, 0xc0, 0x0f, 0xc4, 0xc9, 0x74, 0x68,
	0x8d, 0x78, 0x68, 0xfb, 0x41, 0x48, 0x27, 0x74, 0x6e, 0xf3, 0x91, 0xe0, 0x3e, 0xb7, 0x05, 0xf7,
	0x38, 0x8d, 0x63, 0x3b, 0xe4, 0x1e, 0x9b, 0xd8, 0x6c, 0xc6, 0x22, 0x61, 0xc5, 0x09, 0x17, 0x1c,
	0xab, 0xd2, 0xd2, 0x6f, 0xf9, 0x9c, 0xfb, 0x13, 0x66, 0x4b, 0x73, 0x38, 0x7d, 0x67, 0x8b, 0x20,
	0x64, 0xa9, 0xa0, 0x61, 0x9c, 0xe7, 0xee, 0x7c, 0x56, 0x41, 0x7d, 0x9e, 0xcd, 0xe1, 0x3e, 0xac,
	0x0e, 0x1c, 0xa2, 0x18, 0x8a, 0xd9, 0x72, 0x57, 0x07, 0x0e, 0xbe, 0x07, 0x5b, 0x71, 0xc2, 0x66,
	0x01, 0x9f, 0xa6, 0xaf, 0x58, 0x9a, 0x52, 0x9f, 0xbd, 0xa0, 0xe9, 0x09, 0x59, 0x35, 0x14, 0xb3,
	0xeb, 0x5e, 0xf6, 0x84, 0x0d, 0xe8, 0x50, 0xdf, 0x4f, 0x98, 0x4f, 0x05, 0x1b, 0x38, 0x64, 0x4d,
	0x26, 0xeb, 0x16, 0x7e, 0x04, 0xbd, 0x4a, 0x1e, 0xcf, 0x63, 0x46, 0x5a, 0x86, 0x62, 0xf6, 0xf7,
	0xb7, 0x2d, 0x49, 0x6b, 0x1d, 0xd6, 0xdf, 0xdc, 0x66, 0x14, 0x3f, 0x00, 0xad, 0x82, 0x27, 0xaa,
	0xa1, 0x98, 0x9d, 0x7d, 0xdd, 0xca, 0xd7, 0xb3, 0xca, 0xf5, 0xac, 0xe3, 0x32, 0xe1, 0x2e, 0xc2,
	0x58, 0x87, 0x8d, 0x94, 0x4f, 0x93, 0x51, 0x06, 0xb5, 0x2e, 0xa1, 0x2a, 0x8d, 0x77, 0xa0, 0x97,
	0xff, 0x7e, 0xcb, 0x92, 0x34, 0xe0, 0x11, 0x69, 0x1b, 0x8a, 0xa9, 0xba, 0x4d, 0x13, 0xef, 0x40,
	0x4b, 0x64, 0xb8, 0x1b, 0x12, 0x17, 0x15, 0xb8, 0xf2, 0x6e, 0x12, 0x55, 0xbe, 0x62, 0x02, 0xed,
	0x98, 0xce, 0x27, 0x9c, 0x7a, 0x44, 0x93, 0x35, 0xa5, 0xd4, 0x1f, 0x43, 0xff, 0x75, 0xc2, 0x4f,
	0xd9, 0x48, 0x1c, 0x25, 0x8c, 0x0a, 0xe6, 0xe1, 0x2d, 0x68, 0x45, 0x34, 0x64, 0xe4, 0xe3, 0x35,
	0x43, 0x31, 0x35, 0x57, 0x0a, 0x7c, 0x15, 0x54, 0x41, 0xd3, 0x71, 0x4a, 0xce, 0x5e, 0x1a, 0x6b,
	0x66, 0xd7, 0xcd, 0x95, 0xbe, 0x0b, 0x9d, 0x63, 0x9a, 0x8e, 0x5d, 0x16, 0xf2, 0x19, 0xf3, 0xf0,
	0x75, 0x58, 0xcf, 0xfc, 0x81, 0x43, 0xfe, 0x6e, 0xca, 0x9a, 0x42, 0xea, 0x3b, 0xa0, 0x65, 0xb9,
	0x43, 0xcf, 0x6b, 0xa4, 0x7e, 0xdc, 0x6f, 0xa4, 0xee, 0x56, 0x2c, 0x2e, 0xcb, 0x5a, 0x17, 0x2c,
	0xff, 0x9c, 0x05, 0x8b, 0x8e, 0xaa, 0x98, 0xc3, 0x26, 0x4c, 0x30, 0x4f, 0x7f, 0x98, 0x63, 0x2c,
	0x6f, 0x70, 0x7e, 0xa3, 0xb9, 0x01, 0x0b, 0xf9, 0x69, 0x40, 0xbe, 0xdf, 0x96, 0x6e, 0xae, 0xca,
	0xd1, 0xe5, 0xc2, 0x5f, 0xbd, 0xcb, 0x46, 0xbf, 0x5c, 0xa9, 0x8d, 0xee, 0x7d, 0x53, 0x40, 0xab,
	0x0e, 0x8d, 0x3b, 0xd0, 0x7e, 0x13, 0x8d, 0x23, 0xfe, 0x3e, 0x42, 0x2b, 0x78, 0x6b, 0xf9, 0xaa,
	0xe8, 0xb7, 0x53, 0x33, 0x8b, 0x36, 0xf4, 0xf5, 0x59, 0xcd, 0x2c, 0x96, 0x41, 0x3f, 0x6d, 0xdc,
	0xaf, 0x9d, 0x0b, 0x9d, 0x75, 0x31, 0x6a, 0x9c, 0x19, 0x5d, 0xec, 0xe2, 0x4d, 0xe8, 0x66, 0xce,
	0x20, 0x8c, 0x79, 0x92, 0x0d, 0x7d, 0xda, 0x28, 0x43, 0x65, 0xe1, 0xc5, 0xd1, 0x62, 0x2c, 0x6f,
	0xfb, 0x63, 0xee, 0x3d, 0x81, 0x5e, 0xe3, 0x4b, 0xc6, 0xdb, 0x80, 0x0a, 0xea, 0xca, 0x47, 0x2b,
	0xb8, 0x0b, 0xed, 0x02, 0x0a, 0x9d, 0xdf, 0xc4, 0x1a, 0xb4, 0xb2, 0xbf, 0x41, 0x1f, 0x9e, 0x0e,
	0xd7, 0xe5, 0xe7, 0x7c, 0xf0, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x1d, 0xce, 0x91, 0xf9, 0x03,
	0x00, 0x00,
}
