// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/gimalay/octogo/todoapp/app/viewModel.proto

package app

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LocationType int32

const (
	LocationType_Unknown LocationType = 0
	LocationType_Home    LocationType = 1457
	LocationType_Project LocationType = 1571
	LocationType_Task    LocationType = 1648
)

var LocationType_name = map[int32]string{
	0:    "Unknown",
	1457: "Home",
	1571: "Project",
	1648: "Task",
}

var LocationType_value = map[string]int32{
	"Unknown": 0,
	"Home":    1457,
	"Project": 1571,
	"Task":    1648,
}

func (x LocationType) String() string {
	return proto.EnumName(LocationType_name, int32(x))
}

func (LocationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b90480ee3d88a0d, []int{0}
}

type Settings struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Settings) Reset()         { *m = Settings{} }
func (m *Settings) String() string { return proto.CompactTextString(m) }
func (*Settings) ProtoMessage()    {}
func (*Settings) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b90480ee3d88a0d, []int{0}
}

func (m *Settings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Settings.Unmarshal(m, b)
}
func (m *Settings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Settings.Marshal(b, m, deterministic)
}
func (m *Settings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Settings.Merge(m, src)
}
func (m *Settings) XXX_Size() int {
	return xxx_messageInfo_Settings.Size(m)
}
func (m *Settings) XXX_DiscardUnknown() {
	xxx_messageInfo_Settings.DiscardUnknown(m)
}

var xxx_messageInfo_Settings proto.InternalMessageInfo

type Location struct {
	Type                 LocationType `protobuf:"varint,1,opt,name=type,proto3,enum=app.LocationType" json:"type,omitempty"`
	Payload              []byte       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b90480ee3d88a0d, []int{1}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetType() LocationType {
	if m != nil {
		return m.Type
	}
	return LocationType_Unknown
}

func (m *Location) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Location_Home struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location_Home) Reset()         { *m = Location_Home{} }
func (m *Location_Home) String() string { return proto.CompactTextString(m) }
func (*Location_Home) ProtoMessage()    {}
func (*Location_Home) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b90480ee3d88a0d, []int{1, 0}
}

func (m *Location_Home) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location_Home.Unmarshal(m, b)
}
func (m *Location_Home) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location_Home.Marshal(b, m, deterministic)
}
func (m *Location_Home) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location_Home.Merge(m, src)
}
func (m *Location_Home) XXX_Size() int {
	return xxx_messageInfo_Location_Home.Size(m)
}
func (m *Location_Home) XXX_DiscardUnknown() {
	xxx_messageInfo_Location_Home.DiscardUnknown(m)
}

var xxx_messageInfo_Location_Home proto.InternalMessageInfo

type Location_Project struct {
	ProjectID            []byte   `protobuf:"bytes,2697,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location_Project) Reset()         { *m = Location_Project{} }
func (m *Location_Project) String() string { return proto.CompactTextString(m) }
func (*Location_Project) ProtoMessage()    {}
func (*Location_Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b90480ee3d88a0d, []int{1, 1}
}

func (m *Location_Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location_Project.Unmarshal(m, b)
}
func (m *Location_Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location_Project.Marshal(b, m, deterministic)
}
func (m *Location_Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location_Project.Merge(m, src)
}
func (m *Location_Project) XXX_Size() int {
	return xxx_messageInfo_Location_Project.Size(m)
}
func (m *Location_Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Location_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Location_Project proto.InternalMessageInfo

func (m *Location_Project) GetProjectID() []byte {
	if m != nil {
		return m.ProjectID
	}
	return nil
}

type Location_Task struct {
	TaskID               []byte   `protobuf:"bytes,1717,opt,name=TaskID,proto3" json:"TaskID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location_Task) Reset()         { *m = Location_Task{} }
func (m *Location_Task) String() string { return proto.CompactTextString(m) }
func (*Location_Task) ProtoMessage()    {}
func (*Location_Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b90480ee3d88a0d, []int{1, 2}
}

func (m *Location_Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location_Task.Unmarshal(m, b)
}
func (m *Location_Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location_Task.Marshal(b, m, deterministic)
}
func (m *Location_Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location_Task.Merge(m, src)
}
func (m *Location_Task) XXX_Size() int {
	return xxx_messageInfo_Location_Task.Size(m)
}
func (m *Location_Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Location_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Location_Task proto.InternalMessageInfo

func (m *Location_Task) GetTaskID() []byte {
	if m != nil {
		return m.TaskID
	}
	return nil
}

type Location_AddTask struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location_AddTask) Reset()         { *m = Location_AddTask{} }
func (m *Location_AddTask) String() string { return proto.CompactTextString(m) }
func (*Location_AddTask) ProtoMessage()    {}
func (*Location_AddTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b90480ee3d88a0d, []int{1, 3}
}

func (m *Location_AddTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location_AddTask.Unmarshal(m, b)
}
func (m *Location_AddTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location_AddTask.Marshal(b, m, deterministic)
}
func (m *Location_AddTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location_AddTask.Merge(m, src)
}
func (m *Location_AddTask) XXX_Size() int {
	return xxx_messageInfo_Location_AddTask.Size(m)
}
func (m *Location_AddTask) XXX_DiscardUnknown() {
	xxx_messageInfo_Location_AddTask.DiscardUnknown(m)
}

var xxx_messageInfo_Location_AddTask proto.InternalMessageInfo

type ViewModel struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewModel) Reset()         { *m = ViewModel{} }
func (m *ViewModel) String() string { return proto.CompactTextString(m) }
func (*ViewModel) ProtoMessage()    {}
func (*ViewModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b90480ee3d88a0d, []int{2}
}

func (m *ViewModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewModel.Unmarshal(m, b)
}
func (m *ViewModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewModel.Marshal(b, m, deterministic)
}
func (m *ViewModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewModel.Merge(m, src)
}
func (m *ViewModel) XXX_Size() int {
	return xxx_messageInfo_ViewModel.Size(m)
}
func (m *ViewModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewModel.DiscardUnknown(m)
}

var xxx_messageInfo_ViewModel proto.InternalMessageInfo

type ViewModel_Project struct {
	ID                   []byte                    `protobuf:"bytes,4947,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string                    `protobuf:"bytes,4032,opt,name=name,proto3" json:"name,omitempty"`
	Tasks                []*ViewModel_Project_Task `protobuf:"bytes,8856,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ViewModel_Project) Reset()         { *m = ViewModel_Project{} }
func (m *ViewModel_Project) String() string { return proto.CompactTextString(m) }
func (*ViewModel_Project) ProtoMessage()    {}
func (*ViewModel_Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b90480ee3d88a0d, []int{2, 0}
}

func (m *ViewModel_Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewModel_Project.Unmarshal(m, b)
}
func (m *ViewModel_Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewModel_Project.Marshal(b, m, deterministic)
}
func (m *ViewModel_Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewModel_Project.Merge(m, src)
}
func (m *ViewModel_Project) XXX_Size() int {
	return xxx_messageInfo_ViewModel_Project.Size(m)
}
func (m *ViewModel_Project) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewModel_Project.DiscardUnknown(m)
}

var xxx_messageInfo_ViewModel_Project proto.InternalMessageInfo

func (m *ViewModel_Project) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *ViewModel_Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ViewModel_Project) GetTasks() []*ViewModel_Project_Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type ViewModel_Project_Task struct {
	ID                   []byte   `protobuf:"bytes,5946,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,8336,opt,name=name,proto3" json:"name,omitempty"`
	Emoji                string   `protobuf:"bytes,9790,opt,name=emoji,proto3" json:"emoji,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewModel_Project_Task) Reset()         { *m = ViewModel_Project_Task{} }
func (m *ViewModel_Project_Task) String() string { return proto.CompactTextString(m) }
func (*ViewModel_Project_Task) ProtoMessage()    {}
func (*ViewModel_Project_Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b90480ee3d88a0d, []int{2, 0, 0}
}

func (m *ViewModel_Project_Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewModel_Project_Task.Unmarshal(m, b)
}
func (m *ViewModel_Project_Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewModel_Project_Task.Marshal(b, m, deterministic)
}
func (m *ViewModel_Project_Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewModel_Project_Task.Merge(m, src)
}
func (m *ViewModel_Project_Task) XXX_Size() int {
	return xxx_messageInfo_ViewModel_Project_Task.Size(m)
}
func (m *ViewModel_Project_Task) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewModel_Project_Task.DiscardUnknown(m)
}

var xxx_messageInfo_ViewModel_Project_Task proto.InternalMessageInfo

func (m *ViewModel_Project_Task) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *ViewModel_Project_Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ViewModel_Project_Task) GetEmoji() string {
	if m != nil {
		return m.Emoji
	}
	return ""
}

type ViewModel_Task struct {
	ID                   []byte   `protobuf:"bytes,4987,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,4932,opt,name=name,proto3" json:"name,omitempty"`
	Emoji                string   `protobuf:"bytes,2651,opt,name=emoji,proto3" json:"emoji,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewModel_Task) Reset()         { *m = ViewModel_Task{} }
func (m *ViewModel_Task) String() string { return proto.CompactTextString(m) }
func (*ViewModel_Task) ProtoMessage()    {}
func (*ViewModel_Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b90480ee3d88a0d, []int{2, 1}
}

func (m *ViewModel_Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewModel_Task.Unmarshal(m, b)
}
func (m *ViewModel_Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewModel_Task.Marshal(b, m, deterministic)
}
func (m *ViewModel_Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewModel_Task.Merge(m, src)
}
func (m *ViewModel_Task) XXX_Size() int {
	return xxx_messageInfo_ViewModel_Task.Size(m)
}
func (m *ViewModel_Task) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewModel_Task.DiscardUnknown(m)
}

var xxx_messageInfo_ViewModel_Task proto.InternalMessageInfo

func (m *ViewModel_Task) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *ViewModel_Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ViewModel_Task) GetEmoji() string {
	if m != nil {
		return m.Emoji
	}
	return ""
}

type ViewModel_Home struct {
	Projects             []*ViewModel_Home_Project `protobuf:"bytes,6910,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ViewModel_Home) Reset()         { *m = ViewModel_Home{} }
func (m *ViewModel_Home) String() string { return proto.CompactTextString(m) }
func (*ViewModel_Home) ProtoMessage()    {}
func (*ViewModel_Home) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b90480ee3d88a0d, []int{2, 2}
}

func (m *ViewModel_Home) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewModel_Home.Unmarshal(m, b)
}
func (m *ViewModel_Home) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewModel_Home.Marshal(b, m, deterministic)
}
func (m *ViewModel_Home) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewModel_Home.Merge(m, src)
}
func (m *ViewModel_Home) XXX_Size() int {
	return xxx_messageInfo_ViewModel_Home.Size(m)
}
func (m *ViewModel_Home) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewModel_Home.DiscardUnknown(m)
}

var xxx_messageInfo_ViewModel_Home proto.InternalMessageInfo

func (m *ViewModel_Home) GetProjects() []*ViewModel_Home_Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type ViewModel_Home_Project struct {
	ID                   []byte                         `protobuf:"bytes,4947,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string                         `protobuf:"bytes,4032,opt,name=name,proto3" json:"name,omitempty"`
	Tasks                []*ViewModel_Home_Project_Task `protobuf:"bytes,8856,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ViewModel_Home_Project) Reset()         { *m = ViewModel_Home_Project{} }
func (m *ViewModel_Home_Project) String() string { return proto.CompactTextString(m) }
func (*ViewModel_Home_Project) ProtoMessage()    {}
func (*ViewModel_Home_Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b90480ee3d88a0d, []int{2, 2, 0}
}

func (m *ViewModel_Home_Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewModel_Home_Project.Unmarshal(m, b)
}
func (m *ViewModel_Home_Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewModel_Home_Project.Marshal(b, m, deterministic)
}
func (m *ViewModel_Home_Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewModel_Home_Project.Merge(m, src)
}
func (m *ViewModel_Home_Project) XXX_Size() int {
	return xxx_messageInfo_ViewModel_Home_Project.Size(m)
}
func (m *ViewModel_Home_Project) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewModel_Home_Project.DiscardUnknown(m)
}

var xxx_messageInfo_ViewModel_Home_Project proto.InternalMessageInfo

func (m *ViewModel_Home_Project) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *ViewModel_Home_Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ViewModel_Home_Project) GetTasks() []*ViewModel_Home_Project_Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type ViewModel_Home_Project_Task struct {
	ID                   []byte   `protobuf:"bytes,2946,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,4336,opt,name=name,proto3" json:"name,omitempty"`
	Emoji                string   `protobuf:"bytes,2990,opt,name=emoji,proto3" json:"emoji,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewModel_Home_Project_Task) Reset()         { *m = ViewModel_Home_Project_Task{} }
func (m *ViewModel_Home_Project_Task) String() string { return proto.CompactTextString(m) }
func (*ViewModel_Home_Project_Task) ProtoMessage()    {}
func (*ViewModel_Home_Project_Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b90480ee3d88a0d, []int{2, 2, 0, 0}
}

func (m *ViewModel_Home_Project_Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewModel_Home_Project_Task.Unmarshal(m, b)
}
func (m *ViewModel_Home_Project_Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewModel_Home_Project_Task.Marshal(b, m, deterministic)
}
func (m *ViewModel_Home_Project_Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewModel_Home_Project_Task.Merge(m, src)
}
func (m *ViewModel_Home_Project_Task) XXX_Size() int {
	return xxx_messageInfo_ViewModel_Home_Project_Task.Size(m)
}
func (m *ViewModel_Home_Project_Task) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewModel_Home_Project_Task.DiscardUnknown(m)
}

var xxx_messageInfo_ViewModel_Home_Project_Task proto.InternalMessageInfo

func (m *ViewModel_Home_Project_Task) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *ViewModel_Home_Project_Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ViewModel_Home_Project_Task) GetEmoji() string {
	if m != nil {
		return m.Emoji
	}
	return ""
}

func init() {
	proto.RegisterEnum("app.LocationType", LocationType_name, LocationType_value)
	proto.RegisterType((*Settings)(nil), "app.Settings")
	proto.RegisterType((*Location)(nil), "app.Location")
	proto.RegisterType((*Location_Home)(nil), "app.Location.Home")
	proto.RegisterType((*Location_Project)(nil), "app.Location.Project")
	proto.RegisterType((*Location_Task)(nil), "app.Location.Task")
	proto.RegisterType((*Location_AddTask)(nil), "app.Location.AddTask")
	proto.RegisterType((*ViewModel)(nil), "app.ViewModel")
	proto.RegisterType((*ViewModel_Project)(nil), "app.ViewModel.Project")
	proto.RegisterType((*ViewModel_Project_Task)(nil), "app.ViewModel.Project.Task")
	proto.RegisterType((*ViewModel_Task)(nil), "app.ViewModel.Task")
	proto.RegisterType((*ViewModel_Home)(nil), "app.ViewModel.Home")
	proto.RegisterType((*ViewModel_Home_Project)(nil), "app.ViewModel.Home.Project")
	proto.RegisterType((*ViewModel_Home_Project_Task)(nil), "app.ViewModel.Home.Project.Task")
}

func init() {
	proto.RegisterFile("github.com/gimalay/octogo/todoapp/app/viewModel.proto", fileDescriptor_9b90480ee3d88a0d)
}

var fileDescriptor_9b90480ee3d88a0d = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4d, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0xcf, 0xcc, 0x4d, 0xcc, 0x49, 0xac, 0xd4, 0xcf,
	0x4f, 0x2e, 0xc9, 0x4f, 0xcf, 0xd7, 0x2f, 0xc9, 0x4f, 0xc9, 0x4f, 0x2c, 0x28, 0xd0, 0x07, 0xe1,
	0xb2, 0xcc, 0xd4, 0x72, 0xdf, 0xfc, 0x94, 0xd4, 0x1c, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21,
	0xe6, 0xc4, 0x82, 0x02, 0x25, 0x2e, 0x2e, 0x8e, 0xe0, 0xd4, 0x92, 0x92, 0xcc, 0xbc, 0xf4, 0x62,
	0xa5, 0x95, 0x8c, 0x5c, 0x1c, 0x3e, 0xf9, 0xc9, 0x89, 0x25, 0x99, 0xf9, 0x79, 0x42, 0xaa, 0x5c,
	0x2c, 0x25, 0x95, 0x05, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0x82, 0x7a, 0x89, 0x05,
	0x05, 0x7a, 0x30, 0xc9, 0x90, 0xca, 0x82, 0xd4, 0x20, 0xb0, 0xb4, 0x90, 0x04, 0x17, 0x7b, 0x41,
	0x62, 0x65, 0x4e, 0x7e, 0x62, 0x8a, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x8c, 0x2b, 0xc5,
	0xc6, 0xc5, 0xe2, 0x91, 0x9f, 0x9b, 0x2a, 0xa5, 0xc1, 0xc5, 0x1e, 0x50, 0x94, 0x9f, 0x95, 0x9a,
	0x5c, 0x22, 0x24, 0xcb, 0xc5, 0x09, 0x65, 0x7a, 0xba, 0x48, 0x74, 0x8a, 0x82, 0xd5, 0x23, 0x44,
	0xa4, 0xe4, 0xb9, 0x58, 0x42, 0x12, 0x8b, 0xb3, 0x85, 0xc4, 0xb9, 0xd8, 0x40, 0xb4, 0xa7, 0x8b,
	0xc4, 0x56, 0x5e, 0xb0, 0x1a, 0x28, 0x57, 0x8a, 0x93, 0x8b, 0xdd, 0x31, 0x25, 0x05, 0xc4, 0x51,
	0x7a, 0xc7, 0xcc, 0xc5, 0x19, 0x06, 0xf3, 0x90, 0xd4, 0x0a, 0x46, 0x84, 0x25, 0xfc, 0x5c, 0x4c,
	0x9e, 0x2e, 0x12, 0x97, 0xd5, 0xc0, 0x3a, 0x99, 0x3c, 0x5d, 0x84, 0x84, 0xb9, 0x58, 0xf2, 0x12,
	0x73, 0x53, 0x25, 0x0e, 0xc8, 0x2b, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x39, 0x42, 0x46, 0x5c, 0xac,
	0x25, 0x89, 0xc5, 0xd9, 0xc5, 0x12, 0x33, 0x5c, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0xa4, 0xc1, 0x1e,
	0x84, 0x9b, 0xa8, 0x07, 0x35, 0x4d, 0x0f, 0x64, 0x59, 0x10, 0x44, 0xa9, 0x94, 0x33, 0xd4, 0x7d,
	0x10, 0x1b, 0x76, 0xe9, 0x61, 0xd8, 0x30, 0xc1, 0x11, 0xc9, 0x06, 0x51, 0x2e, 0xd6, 0xd4, 0xdc,
	0xfc, 0xac, 0x4c, 0x89, 0x7d, 0x3e, 0x60, 0x51, 0x08, 0x0f, 0xcd, 0x90, 0xdf, 0x98, 0xce, 0x3c,
	0xa2, 0x86, 0xcd, 0x90, 0xdb, 0x22, 0xc8, 0x86, 0x7c, 0x60, 0x84, 0x04, 0xae, 0x90, 0x05, 0x17,
	0x47, 0x01, 0xc4, 0xa5, 0xc5, 0x12, 0xff, 0x4c, 0xb1, 0xfa, 0x04, 0xa4, 0x0e, 0xe6, 0x9d, 0x20,
	0xb8, 0x6a, 0xa9, 0xb5, 0x24, 0x07, 0x99, 0x39, 0x5a, 0x90, 0x29, 0xe0, 0xb1, 0x08, 0x4f, 0xb8,
	0x35, 0x89, 0x63, 0x58, 0xf3, 0x41, 0x11, 0x9b, 0x97, 0xd7, 0x89, 0x23, 0x79, 0x59, 0xcb, 0x9e,
	0x8b, 0x07, 0x39, 0xf9, 0x09, 0x71, 0x73, 0xb1, 0x87, 0xe6, 0x65, 0xe7, 0xe5, 0x97, 0xe7, 0x09,
	0x30, 0x08, 0x71, 0x42, 0x82, 0x43, 0x60, 0x23, 0xb7, 0x10, 0x0f, 0xdc, 0x5b, 0x02, 0x8b, 0x79,
	0x40, 0x12, 0x20, 0xab, 0x05, 0x3e, 0xf0, 0x38, 0x31, 0xef, 0x62, 0x62, 0x48, 0x62, 0x03, 0x27,
	0x7d, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x15, 0xe7, 0xc5, 0x33, 0x03, 0x00, 0x00,
}
